- name: Funtions
  hosts: local
  connection: local
  vars:
    person: "Ramesh,Suresh,Gopal"
  tasks:
  - name: Learning Functions
    ansible.builtin.debug:
      msg: "Hi {{ person | split(',') }}"
  
      
