- name: Funtions
  hosts: local
  connection: local
  vars:
    person: "Ramesh,Suresh,Gopal"
  tasks:
  - name: Learning Functions
    ansible.builtin.debug:
      msg: "Hi {{ person | split(',') }}"
  
  
  - name: Converting
    ansible.builtin.debug:
    vars:

      Good:
       course: 'Devops'
       duration: '5 hours'
    
      msg: "{{ Good | dict2items }}"
  
      
