- name: Funtions
  hosts: local
  connection: local
  vars:
    person: "Ramesh,Suresh,Gopal"
  tasks:
  - name: Learning Functions
    ansible.builtin.debug:
      msg: "Hi {{ person | split(',') }}"
  
  
  - name: Converting
    
    vars:
      Good:
       course: 'Devops'
       duration: '5 hours'
    ansible.builtin.debug:
    
      msg: "{{ Good | dict2items }}"
  
      
