- name: Installing the packages
  hosts: frontend
  become: yes
  tasks:
  - name: Installing and uninstalling the packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
      
    loop:
    - {name: 'nginx', state: 'present'}
    - {name: 'mysql', state: 'absent'}
    