- name: Install nginx
  hosts: frontend
  tasks:
  - name: Please install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  
  - name: Please start ginx
    ansible.builtin.package:
      name: nginx
      state: started
      enabled: yes