- name: Install nginx
  become: yes
  hosts: frontend

  tasks:
  - name: Please install nginx
    ansible.builtin.package:
      name: nginx
      
      state: present
  
  - name: Please start ginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes